name: rfboost
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.1.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - aom=3.4.0
  - async-timeout=4.0.2
  - attrs=21.4.0
  - blas=2.115
  - blas-devel=3.9.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - click=8.1.3
  - cryptography=37.0.2
  - cudatoolkit=11.6.0
  - ffmpeg=4.3
  - freetype=2.10.4
  - frozenlist=1.3.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-auth-oauthlib=0.4.6
  - icu=70.1
  - idna=3.3
  - importlib-metadata=4.11.4
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.12
  - libdrm=2.4.111
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libgomp=12.1.0
  - libiconv=1.16
  - libidn2=2.3.2
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnsl=2.0.0
  - libpciaccess=0.16
  - libpng=1.6.37
  - libprotobuf=3.19.4
  - libstdcxx-ng=12.1.0
  - libtasn1=4.18.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libuv=1.43.0
  - libva=2.15.0
  - libvpx=1.11.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.14
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - markdown=3.3.7
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - multidict=6.0.2
  - ncurses=6.3
  - nettle=3.6
  - ninja=1.11.0
  - numpy=1.22.4
  - oauthlib=3.2.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1p
  - p11-kit=0.24.1
  - pillow=9.1.1
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.10.5
  - python_abi=3.10
  - pytorch=1.12.0
  - pytorch-mutex=1.0
  - pyu2f=0.1.5
  - readline=8.1.2
  - requests=2.28.0
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - setuptools=62.6.0
  - six=1.16.0
  - sleef=3.5.1
  - sqlite=3.38.5
  - svt-av1=1.1.0
  - tbb=2021.5.0
  - tensorboard=2.9.1
  - tensorboard-plugin-wit=1.8.1
  - tk=8.6.12
  - torchaudio=0.12.0
  - torchvision=0.13.0
  - typing-extensions=4.2.0
  - typing_extensions=4.2.0
  - tzdata=2022a
  - urllib3=1.26.9
  - werkzeug=2.1.2
  - x264=1!161.3030
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yarl=1.7.2
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip
  - pip:
    - asttokens==2.0.5
    - astunparse==1.6.3
    - backcall==0.2.0
    - cachetools==5.2.0
    - certifi==2022.6.15
    - cycler==0.11.0
    - debugpy==1.6.0
    - decorator==5.1.1
    - einops==0.4.1
    - entrypoints==0.4
    - executing==0.8.3
    - flatbuffers==1.12
    - fonttools==4.33.3
    - gast==0.4.0
    - google-auth==2.9.0
    - google-pasta==0.2.0
    - grpcio==1.47.0
    - gviz-api==1.10.0
    - h5py==3.7.0
    - imbalanced-learn==0.9.1
    - imblearn==0.0
    - ipykernel==6.15.0
    - ipython==8.4.0
    - jedi==0.18.1
    - joblib==1.1.0
    - jupyter-client==7.3.4
    - jupyter-core==4.10.0
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.3
    - libclang==14.0.1
    - mat73==0.59
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.3
    - nest-asyncio==1.5.5
    - nvidia-dali-cuda110==1.15.0
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.4.3
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pip==22.1.2
    - prefetch-generator==1.0.1
    - prompt-toolkit==3.0.30
    - protobuf==3.19.4
    - psutil==5.9.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1-modules==0.2.8
    - pygments==2.12.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==6.0
    - pyzmq==23.2.0
    - scikit-learn==1.1.1
    - scipy==1.9.0
    - stack-data==0.3.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-profile==2.8.0
    - tensorflow-estimator==2.9.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - torch-tb-profiler==0.4.0
    - torchmetrics==0.9.3
    - torchsummary==1.5.1
    - tornado==6.1
    - tqdm==4.64.0
    - traitlets==5.3.0
    - wcwidth==0.2.5
    - wheel==0.37.1
    - wrapt==1.14.1
